// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSF_1Sh2i2YY_DUHJkSlRhPmf8bWi_MQU',
    appId: '1:722588514608:web:47a6264dbf756f704030f5',
    messagingSenderId: '722588514608',
    projectId: 'flutter-e-commerce-1bfe2',
    authDomain: 'flutter-e-commerce-1bfe2.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-1bfe2.appspot.com',
    measurementId: 'G-Y0THQNJJMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2PTvXfxVTiIgLYyyeEkZ6P0Ty9y-3RkA',
    appId: '1:722588514608:android:16ecbf8e9053eac24030f5',
    messagingSenderId: '722588514608',
    projectId: 'flutter-e-commerce-1bfe2',
    storageBucket: 'flutter-e-commerce-1bfe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEHTS9ZwHiziczBnR2yNYnLH3-yBelNRw',
    appId: '1:722588514608:ios:69cd2784f1d994dd4030f5',
    messagingSenderId: '722588514608',
    projectId: 'flutter-e-commerce-1bfe2',
    storageBucket: 'flutter-e-commerce-1bfe2.appspot.com',
    androidClientId: '722588514608-k12hr26a5kgr4ndtbt58mt1gvualt1b2.apps.googleusercontent.com',
    iosClientId: '722588514608-mg8ne49ou2o47frg9ovm7a11ndp6e0ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEHTS9ZwHiziczBnR2yNYnLH3-yBelNRw',
    appId: '1:722588514608:ios:69cd2784f1d994dd4030f5',
    messagingSenderId: '722588514608',
    projectId: 'flutter-e-commerce-1bfe2',
    storageBucket: 'flutter-e-commerce-1bfe2.appspot.com',
    androidClientId: '722588514608-k12hr26a5kgr4ndtbt58mt1gvualt1b2.apps.googleusercontent.com',
    iosClientId: '722588514608-mg8ne49ou2o47frg9ovm7a11ndp6e0ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );
}
